### ISSUE TITLE
Support canvas sizes other than 64x64

### ISSUE THREAD

**Issue by jackschaedler** [jackschaedler/goya#15]
Probably don't need arbitrary sizes just yet. I think the app should maybe support:

16x16
32x32
64x62

as a starting point.

**Comment by jackschaedler** [comment]
Done. Also added support for 24x24.

**Comment by danecjensen** [comment]
For supporting a rectangular canvas I think you need to change this line: https://github.com/jackschaedler/goya/blob/master/src/cljs/goya/canvasdrawing.cljs#L24 to width instead of height.  I would make a pull request but it was such a tiny change.
