### ISSUE TITLE
Problems in Safari 8

### ISSUE THREAD

**Issue by ghost** [jackschaedler/goya#37]
A more helpful message would be great :) 

![safari](https://cloud.githubusercontent.com/assets/8317250/6075393/aa160d16-ae14-11e4-9d53-632cdf22fc6b.png)

What are the features that goya uses not implemented in Safari?

Cheers.

**Comment by jackschaedler** [comment]
Last time I checked, Safari didn't support the "color" input type. I don't really want to provide a work around using some 3rd party js library here.

**Comment by ghost** [comment]
:+1:
